package entities;
// Generated 12 2, 21 8:33:13 PM by Hibernate Tools 4.3.1



/**
 * DiseaseSymptomsMap generated by hbm2java
 */
public class DiseaseSymptomsMap  implements java.io.Serializable {


     private Integer id;
     private DogDiseases dogDiseases;
     private SymptomsList symptomsList;

    public DiseaseSymptomsMap() {
    }

    public DiseaseSymptomsMap(DogDiseases dogDiseases, SymptomsList symptomsList) {
       this.dogDiseases = dogDiseases;
       this.symptomsList = symptomsList;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public DogDiseases getDogDiseases() {
        return this.dogDiseases;
    }
    
    public void setDogDiseases(DogDiseases dogDiseases) {
        this.dogDiseases = dogDiseases;
    }
    public SymptomsList getSymptomsList() {
        return this.symptomsList;
    }
    
    public void setSymptomsList(SymptomsList symptomsList) {
        this.symptomsList = symptomsList;
    }




}


