    package entities;
// Generated 11 15, 21 8:31:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.Id;




/**
 * DiseaseSymptomsMap generated by hbm2java
 */
@Entity
public class DiseaseSymptomsMap  implements java.io.Serializable {


    @Id
    private Integer id;
     
    private DogDiseases dogDiseases;
     
    private SymptomsList symptomsList;

    public DiseaseSymptomsMap() {
    }

    public DiseaseSymptomsMap(DogDiseases dogDiseases, SymptomsList symptomsList) {
       this.dogDiseases = dogDiseases;
       this.symptomsList = symptomsList;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public DogDiseases getDogDiseases() {
        return this.dogDiseases;
    }
    
    public void setDogDiseases(DogDiseases dogDiseases) {
        this.dogDiseases = dogDiseases;
    }
    
    public SymptomsList getSymptomsList() {
        return this.symptomsList;
    }
    
    public void setSymptomsList(SymptomsList symptomsList) {
        this.symptomsList = symptomsList;
    }
}


