package entities;
// Generated 12 2, 21 8:33:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SymptomsList generated by hbm2java
 */
public class SymptomsList  implements java.io.Serializable {


     private Integer id;
     private String symptoms;
     private Set diseaseSymptomsMaps = new HashSet(0);

    public SymptomsList() {
    }

	
    public SymptomsList(String symptoms) {
        this.symptoms = symptoms;
    }
    public SymptomsList(String symptoms, Set diseaseSymptomsMaps) {
       this.symptoms = symptoms;
       this.diseaseSymptomsMaps = diseaseSymptomsMaps;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSymptoms() {
        return this.symptoms;
    }
    
    public void setSymptoms(String symptoms) {
        this.symptoms = symptoms;
    }
    public Set getDiseaseSymptomsMaps() {
        return this.diseaseSymptomsMaps;
    }
    
    public void setDiseaseSymptomsMaps(Set diseaseSymptomsMaps) {
        this.diseaseSymptomsMaps = diseaseSymptomsMaps;
    }




}


